version: '2'

# same as 
# docker run -p 80:4000 -v $(pwd):/site harbudsan/nginx-serve

services:
  hbsnginx:
    image: harbudsan/nginx-serve
    volumes:
      - .:/site
    ports:
      - '80:4000'


